---
- name: add certbot PPA
  become: yes
  apt_repository:
    repo: ppa:certbot/certbot
  register: certbot_repo

- name: install certbot
  become: yes
  apt:
    name: certbot
    state: latest
    update-cache: '{{ certbot_repo.changed }}'

- name: run certbot to get a key and certificate
  command: certbot certonly --webroot -w {{ public_dir }} {{ letsencrypt_domain_args }} --email={{ admin_email }} --agree-tos --text --quiet --no-self-upgrade
  args:
    creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  vars:
    letsencrypt_domain_args: "{% for d in letsencrypt_domains|default([domain, 'www.'+domain]) %} -d {{ d }}{% endfor %}"

- name: link letsencrypt certificate
  file:
    src: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
    dest: "{{ ssl_dir }}/{{ domain }}.crt"
    state: link
    force: yes
  notify: reload nginx

- name: link letsencrypt key
  file:
    src: /etc/letsencrypt/live/{{ domain }}/privkey.pem
    dest: "{{ ssl_dir }}/{{ domain }}.key"
    state: link
    force: yes
  notify: reload nginx

# The PPA package sets up certificate renewal for us, so remove any previous cron job we might have set up.
- name: remove previous letsencrypt renewal cron job
  cron:
    state: absent
    name: renew_certbot
    cron_file: letsencrypt
    user: root
